name: Build

on: [push, pull_request]

jobs:
  build-php:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: "Install Composer dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Run Rector"
        run: composer rector -- process --no-progress-bar --dry-run src/RectorBug.php
